exports.up = function (knex) {
    knex.schema.hasTable('entrada').then(function (exists) {
        if (!exists) {
            return knex.schema.createTable("entrada", function (table) {
                table.increments();
                table.text("dataAtual").notNullable();
                table.text("conferente").notNullable();
                //
                table.text("filialOrigem_1").notNullable();
                table.text("notaFiscal_1").notNullable();
                table.text("codigo_1").notNullable();
                table.text("descricaoProduto_1").notNullable();
                table.text("quantidadeProduto_1").notNullable();
                table.text("filialDestino_1").notNullable();
                table.text("observacao_1");
                //
                table.text("filialOrigem_2");
                table.text("notaFiscal_2");
                table.text("codigo_2");
                table.text("descricaoProduto_2");
                table.text("quantidadeProduto_2");
                table.text("filialDestino_2").notNullable();
                table.text("observacao_2");
                //
                table.text("filialOrigem_3");
                table.text("notaFiscal_3");
                table.text("codigo_3");
                table.text("descricaoProduto_3");
                table.text("quantidadeProduto_3");
                table.text("filialDestino_3").notNullable();
                table.text("observacao_3");
                //
                table.text("filialOrigem_4");
                table.text("notaFiscal_4");
                table.text("codigo_4");
                table.text("descricaoProduto_4");
                table.text("quantidadeProduto_4");
                table.text("filialDestino_4").notNullable();
                table.text("observacao_4");
                //
                table.text("filialOrigem_5");
                table.text("notaFiscal_5");
                table.text("codigo_5");
                table.text("descricaoProduto_5");
                table.text("quantidadeProduto_5");
                table.text("filialDestino_5").notNullable();
                table.text("observacao_5");
                //
                table.text("filialOrigem_6");
                table.text("notaFiscal_6");
                table.text("codigo_6");
                table.text("descricaoProduto_6");
                table.text("quantidadeProduto_6");
                table.text("filialDestino_6").notNullable();
                table.text("observacao_6");
                //
                table.text("filialOrigem_7");
                table.text("notaFiscal_7");
                table.text("codigo_7");
                table.text("descricaoProduto_7");
                table.text("quantidadeProduto_7");
                table.text("filialDestino_7").notNullable();
                table.text("observacao_7");
                //
                table.text("filialOrigem_8");
                table.text("notaFiscal_8");
                table.text("codigo_8");
                table.text("descricaoProduto_8");
                table.text("quantidadeProduto_8");
                table.text("filialDestino_8").notNullable();
                table.text("observacao_8");
                //
                table.text("filialOrigem_9");
                table.text("notaFiscal_9");
                table.text("codigo_9");
                table.text("descricaoProduto_9");
                table.text("quantidadeProduto_9");
                table.text("filialDestino_9").notNullable();
                table.text("observacao_9");
                //
                table.text("filialOrigem_10");
                table.text("notaFiscal_10");
                table.text("codigo_10");
                table.text("descricaoProduto_10");
                table.text("quantidadeProduto_10");
                table.text("filialDestino_10").notNullable();
                table.text("observacao_10");
                //
                table.text("filialOrigem_11");
                table.text("notaFiscal_11");
                table.text("codigo_11");
                table.text("descricaoProduto_11");
                table.text("quantidadeProduto_11");
                table.text("filialDestino_11").notNullable();
                table.text("observacao_11");
                //
                table.text("filialOrigem_12");
                table.text("notaFiscal_12");
                table.text("codigo_12");
                table.text("descricaoProduto_12");
                table.text("quantidadeProduto_12");
                table.text("filialDestino_12").notNullable();
                table.text("observacao_12");
                //
                table.text("filialOrigem_13");
                table.text("notaFiscal_13");
                table.text("codigo_13");
                table.text("descricaoProduto_13");
                table.text("quantidadeProduto_13");
                table.text("filialDestino_13").notNullable();
                table.text("observacao_13");
                //
                table.text("filialOrigem_14");
                table.text("notaFiscal_14");
                table.text("codigo_14");
                table.text("descricaoProduto_14");
                table.text("quantidadeProduto_14");
                table.text("filialDestino_14").notNullable();
                table.text("observacao_14");
                //
                table.text("filialOrigem_15");
                table.text("notaFiscal_15");
                table.text("codigo_15");
                table.text("descricaoProduto_15");
                table.text("quantidadeProduto_15");
                table.text("filialDestino_15").notNullable();
                table.text("observacao_15");
                //
                table.text("filialOrigem_16");
                table.text("notaFiscal_16");
                table.text("codigo_16");
                table.text("descricaoProduto_16");
                table.text("quantidadeProduto_16");
                table.text("filialDestino_16").notNullable();
                table.text("observacao_16");
                //
                table.text("filialOrigem_17");
                table.text("notaFiscal_17");
                table.text("codigo_17");
                table.text("descricaoProduto_17");
                table.text("quantidadeProduto_17");
                table.text("filialDestino_17").notNullable();
                table.text("observacao_17");
                //
                table.text("filialOrigem_18");
                table.text("notaFiscal_18");
                table.text("codigo_18");
                table.text("descricaoProduto_18");
                table.text("quantidadeProduto_18");
                table.text("filialDestino_18").notNullable();
                table.text("observacao_18");
                //
                table.text("filialOrigem_19");
                table.text("notaFiscal_19");
                table.text("codigo_19");
                table.text("descricaoProduto_19");
                table.text("quantidadeProduto_19");
                table.text("filialDestino_19").notNullable();
                table.text("observacao_19");
                //
                table.text("filialOrigem_20");
                table.text("notaFiscal_20");
                table.text("codigo_20");
                table.text("descricaoProduto_20");
                table.text("quantidadeProduto_20");
                table.text("filialDestino_20").notNullable();
                table.text("observacao_20");
                //
                table.string("created_at");
                table.string("updated_at");
            });
        };
    })
}

exports.down = function (knex) {
    return knex.schema.dropTable("transferencias");
};
